CREATE DATABASE "pgsqlmedium" WITH TEMPLATE = template0 ENCODING 'UTF8';
\c pgsqlmedium
BEGIN;

CREATE TABLE "user_" (
  id SERIAL PRIMARY KEY,
  firstname varchar(255) default NULL,
  lastname varchar(255) default NULL,
  age integer NULL,
  sexe varchar(255) default NULL,
  city varchar(255),
  idcategory integer NULL
);

CREATE TABLE "category_" (
  id SERIAL PRIMARY KEY,
  name varchar(255)
);

INSERT INTO "category_" (name) VALUES ('Nibh Incorporated'),('Varius Institute'),('Dictum Incorporated'),('Arcu Imperdiet LLC'),('Dictum Incorporated'),('Non Lobortis Corp.'),('Quam Ltd'),('Mattis Incorporated'),('A Consulting'),('Ipsum Dolor Sit LLP');
INSERT INTO "category_" (name) VALUES ('Sed Sapien Nunc Incorporated'),('Amet Metus Associates'),('Semper Tellus PC'),('Phasellus Consulting'),('Eu Tellus Limited'),('Fusce Dolor Inc.'),('At Sem Industries'),('Dictum LLP'),('Cras LLP'),('Nec Quam Curabitur Foundation');
INSERT INTO "category_" (name) VALUES ('Primis In Faucibus Industries'),('Sit Industries'),('Cursus Integer Incorporated'),('Gravida Incorporated'),('Quis LLP'),('Erat Inc.'),('Nulla Vulputate Dui Limited'),('Sem PC'),('Semper Auctor Mauris Industries'),('Curabitur Vel Lectus Industries');
INSERT INTO "category_" (name) VALUES ('Nunc Incorporated'),('Lacus Aliquam LLP'),('Dui Augue Eu Corporation'),('Nisi Aenean Eget PC'),('Nullam Associates'),('Dolor Dapibus Gravida PC'),('Etiam Imperdiet Dictum Industries'),('Dapibus Foundation'),('Nulla At Corp.'),('Dolor PC');
INSERT INTO "category_" (name) VALUES ('Libero Donec Consectetuer Foundation'),('Hendrerit Donec Porttitor Foundation'),('Enim Inc.'),('Orci Incorporated'),('Elit Consulting'),('Risus Nulla Corp.'),('Mauris Blandit Limited'),('Lectus Ante Company'),('Enim Nunc Ut PC'),('Id Magna Associates');
INSERT INTO "category_" (name) VALUES ('Class Aptent Limited'),('Vitae Inc.'),('Dictum Eu Placerat Inc.'),('Orci Ut Semper LLC'),('Dolor Nonummy PC'),('Nisl Elementum Purus Corp.'),('Nunc LLC'),('Vulputate Mauris Institute'),('Phasellus Associates'),('Sodales Elit Incorporated');
INSERT INTO "category_" (name) VALUES ('Augue Consulting'),('Cras Pellentesque Sed PC'),('At Associates'),('Est Company'),('Eget Odio Aliquam Corp.'),('Fringilla Porttitor LLP'),('Egestas A Dui Corporation'),('In Molestie Tortor Limited'),('Luctus Industries'),('Vitae Erat Vel Corp.');
INSERT INTO "category_" (name) VALUES ('Pellentesque Tincidunt Company'),('Parturient LLP'),('Lectus Company'),('Vitae Aliquet Nec Inc.'),('Varius Nam Porttitor Limited'),('Et Magnis Corporation'),('Eu Eleifend PC'),('Mollis Duis LLP'),('Metus Ltd'),('Rutrum Eu Incorporated');
INSERT INTO "category_" (name) VALUES ('Nec Company'),('Nibh Vulputate Mauris Industries'),('Nisi Mauris Ltd'),('Nascetur Ridiculus Mus Institute'),('Posuere Cubilia Curae; Company'),('Tristique Corporation'),('Nec Incorporated'),('Dui Inc.'),('In Industries'),('Sem Industries');
INSERT INTO "category_" (name) VALUES ('Elit Inc.'),('Aliquet Corporation'),('Eu Ultrices LLP'),('Consectetuer Euismod LLC'),('In Ornare Industries'),('Vitae Associates'),('Non Corporation'),('Quisque Nonummy LLP'),('A Felis Ullamcorper Associates'),('Amet Metus Aliquam Company');


INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Allistair','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Winter','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Allistair','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Allistair','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Allistair','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Allistair','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Allistair','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Allistair','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Allistair','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Kamal','Heath',43,'0','Pointe-du-Lac',59),('Harding','Park',62,'1','East Kilbride',43),('Marsden','Stevens',71,'0','Cartago',100),('Hiram','Newman',72,'0','Penhold',29),('Lenore','Simmons',81,'1','Dera Ghazi Khan',63),('Doris','Reid',5,'1','Aisén',76),('Harding','Johns',76,'1','Viesville',61),('Calvin','Mcbride',11,'0','Lewiston',76),('Amanda','English',67,'1','Reus',94),('Mara','Delacruz',73,'1','Batu',2);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Blake','Harrington',48,'1','Blankenberge',100),('Melyssa','Rosario',30,'1','Ragogna',27),('Keaton','Mcgee',57,'0','Beho',12),('Piper','Franks',66,'0','Los Álamos',22),('Jordan','Mendez',96,'1','Huntingdon',73),('Mannix','Dorsey',3,'0','Banjar',60),('Barrett','Cohen',42,'0','Yaxley',84),('Sacha','Trujillo',77,'0','Calvello',1),('Janna','Lopez',96,'1','Macchia Valfortore',86),('Yuli','Osborne',27,'0','Souvret',66);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Chloe','Bruce',99,'0','Kirov',3),('Aidan','Holland',65,'0','Amstetten',99),('Cody','Gallagher',63,'0','Kleinmachnow',3),('Peter','Duffy',9,'1','General Lagos',2),('Hop','Rhodes',48,'0','Alix',14),('Tad','Thompson',71,'0','Ragnies',48),('Rowan','Bowers',52,'0','Zandhoven',28),('Vladimir','Puckett',80,'0','Mirpur',54),('Hollee','Bender',13,'1','Lang',59),('Samson','Page',5,'1','Quilleco',88);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Christopher','Cote',69,'1','Pulle',38),('Salvador','Hayes',39,'1','Rengo',56),('Oscar','Barton',88,'0','Segovia',2),('Lars','Blake',5,'0','Lummen',91),('Macy','Burris',16,'0','Beringen',93),('Pearl','Flores',20,'0','Spruce Grove',68),('Holmes','West',7,'0','Armadale',39),('Alma','Irwin',33,'1','Marcinelle',69),('Russell','Montgomery',20,'0','Bellefontaine',18),('Georgia','Vaughn',75,'0','Landelies',9);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Axel','Mcdonald',45,'0','Lansing',1),('Salvador','Walter',88,'1','Rimouski',61),('Linda','Christian',3,'1','Dendermonde',64),('Colin','Hanson',98,'1','Lafayette',1),('Austin','Cabrera',89,'1','Pekanbaru',78),('Claire','Nixon',46,'0','Aurora',4),('Martin','Ewing',51,'1','Gimcheon',12),('Micah','Wong',86,'0','Arrone',45),('Avye','Brown',12,'0','Ciudad Madero',46),('Cade','Weaver',47,'1','Neerharen',60);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Allistair','Norton',9,'0','Monclova',91),('Hillary','Dillard',52,'1','Haridwar',15),('Orlando','Stanley',54,'1','Lyubertsy',15),('Norman','Shields',90,'0','María Elena',90),('Sharon','Levine',22,'0','San Fele',22),('Rhoda','Lane',90,'1','Dorval',9),('Jameson','Rocha',56,'0','Chastre',31),('Amber','Ford',9,'1','Temse',45),('Beau','Wheeler',96,'0','Porirua',9),('Zenaida','Lloyd',94,'1','Cicagna',25);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Althea','Patterson',8,'0','Essex',88),('Elmo','Beach',25,'1','Waasmunster',25),('Alec','Donaldson',51,'1','Dubna',86),('Germane','Hurst',19,'1','Retiro',94),('Jaden','Buckner',4,'1','Kearny',66),('Raven','Petersen',49,'0','Le Mans',80),('Brent','May',58,'0','Gunsan',47),('Chiquita','Turner',23,'1','Ucluelet',25),('Lev','Gould',18,'0','Lowell',41),('Carson','Flores',66,'0','Tual',6);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Hakeem','Copeland',50,'0','Morgex',56),('Zenaida','Delgado',99,'1','Dorval',66),('Damian','Ballard',86,'0','Winterswijk',59),('Alexandra','Solomon',94,'0','Jauche',53),('Axel','Cole',29,'1','West Vancouver',53),('Madonna','Reese',17,'1','Shipshaw',42),('Amaya','Griffith',19,'0','Ciudad Valles',11),('Cynthia','Oneill',16,'0','Ried im Innkreis',83),('Darius','Noel',44,'1','San Pablo',29),('Igor','Mooney',4,'1','Boorsem',18);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Dorothy','Cochran',69,'0','Calamar',59),('Emi','Potts',19,'0','Ghizer',95),('Mercedes','Conway',38,'1','Middlesbrough',37),('Maxine','Strickland',38,'1','Vigo',71),('Mercedes','Barron',60,'0','Colonnella',23),('Emily','Grant',69,'0','Oberursel',77),('Zena','Witt',15,'1','Minucciano',73),('Jaime','Guerra',26,'1','Lexington',1),('Harper','Russo',46,'0','Altamura',39),('Valentine','Mosley',70,'1','Minto',76);
INSERT INTO "user_" (firstname,lastname,age,sexe,city,idcategory) VALUES ('Zeph','West',58,'1','Ostra Vetere',68),('Berk','Battle',79,'1','Polpenazze del Garda',95),('Gareth','Raymond',7,'1','Balashikha',47),('Carl','Ashley',33,'1','Invergordon',90),('Rooney','Donaldson',58,'0','Warrnambool',51),('Aladdin','Hewitt',62,'1','Kingston',56),('Kaseem','Ortega',27,'1','Barrhead',15),('Flavia','Hicks',38,'0','Ternat',36),('Adam','Duran',64,'0','Vilna',26),('Matthew','Porter',35,'1','Purén',65);

ALTER TABLE "user_" 
ADD CONSTRAINT "fk_user_cat" 
FOREIGN KEY (idcategory) 
REFERENCES "category_" (id);

COMMIT;